server:
  port: 8030

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka
spring:
  cloud:
    gateway:
      routes:
        - id: provide
          uri: lb://service-provide
          predicates:
            - Path=/provide/**
  application:
    name: gateway
ribbon:
  eureka:
    enabled: true